tags:
    resource: "@TagsBundle/Controller/"
    type:     annotation
    prefix:   /

dashboard:
    resource: "@DashboardBundle/Controller/"
    type:     annotation
    prefix:   /

securite:
    resource: "@SecuriteBundle/Controller/"
    type:     annotation
    prefix:   /

recette:
    resource: "@RecetteBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
